<div class='listHeader rel blackBtnT p10 white' id='listHeader'>
    <div class='tab'>Listings</div>
    <div class='abs filterBox p10' id='FilterListings'>
        <div class='resultLink fl w49 blue listSelected' data-filter='enableRentFilter'>
            Rentals
        </div>
        <div class='resultLink fr w49 red clearfix' data-filter='enableRoomFilter'>
            Roommates
        </div>
        <div class='abs ListFilters w100'>
            <div class='rel w100 whitebg' id='RentalFilter'>
                <div>
                    Rental filters
                </div>
                <div class='closeFilter abs b0 bluebg'>
                    CLOSE
                </div>
            </div>
            <div class='rel w100 whitebg' id='RoommateFilter'>
                <div>
                    Roommate filters
                </div>
                <div class='closeFilter abs b0 bluebg'>
                    CLOSE
                </div>
            </div>
        </div>
    </div>
</div>