<div class='rel centertext hide'>
    <div class='nTab bluebg white' data-mode='0'>
        Restaurants
    </div>
    <div class='nTab bluebg white' data-mode='1'>
        Bank/ATM
    </div>
    <div class='nTab bluebg white' data-mode='2'>
        Movie
    </div>
    <div class='nTab bluebg white' data-mode='3'>
        Nightlife
    </div>
    <div class='clear'></div>
</div>
<div class='rel h100'>
    <div class='fl w50 h100 orangeBtnT white p10'>
        Explore
    </div>
    <div class='fr w50 h100 blueBtnT white p10 clearfix'>
        Connect
    </div>
</div>